### ISSUE TITLE
Transforming a parametric term

### ISSUE THREAD

**Issue by scra88le** [stefanocoretta/tidymv#14]
Great package!  I have a model:

```
m1 <- gam(CU ~ s(X,Y, k=20) + E, offset = logd, 
  family = poisson,
  link = log,
  data = my_data)
```

I can plot the parametric term:

```
library(tidymv)
plot_smooths(model = m1, 
             # Plot the smooth of E
             series = E) 
```
and get a plot as expected:

![image](https://user-images.githubusercontent.com/1573983/81431326-de3e5d00-9158-11ea-8ecb-1a5325f060d0.png)

I'm trying to plot the response as follows:

```
plot_smooths(model = m1, 
             # Plot the smooth of E
             series = E,
             transform = exp) 
```
And now I get a strange plot:

![image](https://user-images.githubusercontent.com/1573983/81431482-1776cd00-9159-11ea-9682-fe25eb153682.png)

The x and y axis look correct, and the bottom link looks correct, but there seems to be a top line that shouldn't be there. Am I doing anything wrong?

**Comment by stefanocoretta** [comment]
Hi! I suspect that the use of `offset` in the call to `gam()` is creating an unexpected behaviour with `plot_smooths()`. Basically, the straight line that you see in the second plot is `geom_path()` linking the first point on the left to the last on the right of the predicted curve.

I'll have a look into this. In the meantime, you can get the predictions with `predict_gam()` (you can check out the vignette "predict-gam" for more info).

Sorry for the incovenience and thanks for trying the package!

**Comment by scra88le** [comment]
I thought it might be something like that. Thanks for the advice on `predict_gam`. I did manage to get the same result from `get_gam_predictions`. Thanks again.
