### ISSUE TITLE
logged variable

### ISSUE THREAD

**Issue by ashenkin** [stefanocoretta/tidymv#16]
Hi there,
Thanks for your cool package!  Wondering how I can refer to a logged column - any thoughts?  thanks!

```
set.seed(10)
data <- gamSim(4)
#> Factor `by' variable example
model <- gam(
    y ~
        fac +
        s(log(x2)) +
        s(log(x2), by = fac) +
        s(x0),
    data = data
)

plot_smooths(
    model = model,
    series = log(x2),
    comparison = fac
)
```

**Comment by stefanocoretta** [comment]
Could you try with backticks? `` `log(x2)` ``

If that doesn't work, I'll have a more thorough look in the coming weeks (I'm in the process of moving to a new country and I am a bit short in time!).

**Comment by ashenkin** [comment]
Thanks Stefano - still the same result unfortunately (i.e. ```
Error: Can't subset columns that don't exist.
x Column `log(x2)` doesn't exist.
```)
Best of luck with the move!!  No fun, I know.

**Comment by stefanocoretta** [comment]
Right, I think the name is sanitised under the hood (I quite don't remember how it's done, but I guess parentheses are stripped, so maybe `logx2` might work).

**Comment by ashenkin** [comment]
Thanks.  `logx2 ` fails as well.

![image](https://user-images.githubusercontent.com/1608945/132313495-8c1e5296-74b4-4082-98c2-90f4e067be00.png)

**Comment by stefanocoretta** [comment]
Unfortunately I can't find a sensible way to fix this. You can try and install the developmental version of the package and use `predict_gam()` with `type = "terms"`. This returns predictions of individual terms. You can sum them and log them.
