### ISSUE TITLE
Extracting difference values using `get_smooths_difference()`

### ISSUE THREAD

**Issue by Dallak** [stefanocoretta/tidymv#18]
Hi,
Thanks for the great package!

I am just wondering why when using `get_smooths_difference()` it just gets the smooth differences for one speaker only, though I have many speakers and would love to get all their values together.
Note sure if this relates to how I structure the model,  here it is just in case.

```
model_1 = gam(F0 ~ 
                    voicing_manner_vowel +
                    s(time) + 
                    s(time, speaker, bs = "re")+
                    s(time, by =voicing_manner_vowel, bs = 'cr', k = 4),
                   data = data, method = "ML")
```
Thanks in advance!

**Comment by stefanocoretta** [comment]
Hi! Sorry for the ridiculous delay in replying.

I'm planning a complete rewrite of the package which might address this issue. For the time being, there is unfortunately no straightforward solution.
