### ISSUE TITLE
predict_gam() standard error and confidence interval

### ISSUE THREAD

**Issue by daniostr** [stefanocoretta/tidymv#20]
Hi,

Thank you for the super easy-to-use package! 
Can you please give me some intuition why computing predictions and CI for gam models is challenging? 
Based on what formula do you compute the standard error? 
And to make sure, the results are confidence intervals and not predictive intervals, correct? 

Thanks,
Daniel

**Comment by stefanocoretta** [comment]
Hi! Thanks for using the package.

It is not difficult to obtain predictions from GAMs per se, it's just that the mgcv package is designed in a way that allows great flexibility and efficiency which makes obtaining predictions less straightforward than for example lmer.

The SE is returned by mgcv, so I'd suggest checking the documentation of `mgcv::predict.gam`.

The returned CIs are equivalent to Bayesian Credible Intervals, based on the mgcv documentation.

**Comment by daniostr** [comment]
If it should be easy to get standard CI, why do we estimate Bayesian credible intervals instead?
And by any chance, do you know why the perdict_gam might produce the following error - Error in if (term_name %in% names(values)) { : argument is of length zero

Thanks a lot!
